### ISSUE TITLE
[Feature] Allow Expression Language in value

### ISSUE THREAD

**Issue by syl20b** [synolia/SyliusGDPRPlugin#33]
Hello and thank you for this plugin.  

I'd like to control / standardize the value of anonymized properties.
In order to add such a feature, the use of the Expression Language could be an asset:

```yaml
Sylius\Component\Core\Model\Customer:
    properties:
        email:
            value: '@="anonimized-" ~ object.getId() ~ "@domain.tld"'
```

Here, the use of `@=` prefix means that the value must be considered as an expression.

What do you think about that ?

Regards,
